language: node_js

branches:
    # We need to whitelist the branches which we want to have "push" automation.
    # Pull request automation is not constrained to this set of branches.
    only:
        - master
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: '4'
      env: CXX=g++-4.8 TEST_SUITE=test
    - os: linux
      node_js: '6'
      env: CXX=g++-4.8 TEST_SUITE=test
    - os: linux
      node_js: '8'
      env: CXX=g++-4.8 TEST_SUITE=test
    - os: linux
      node_js: '10'
      env: CXX=g++-4.8 TEST_SUITE=test
    - os: linux
      node_js: '12'
      env: CXX=g++-4.8 TEST_SUITE=test
    - os: linux
      node_js: '12'
      env: CXX=g++-4.8 TEST_SUITE=coveralls
script: npm run $TEST_SUITE
