workflows:
  version: 2.1
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - node-v14
      - node-v16:
          run_coveralls: true
      - node-v17

version: 2.1

commands:
  show-npm-version:
    steps:
      - run:
          name: Versions
          command: npm version

  install-dependencies:
    parameters:
      cache-id:
        type: string
      path:
        type: string
        default: .
      package-manager:
        type: string
        default: npm
      dependency-file:
        type: string
        default: package.json
    steps:
      - restore_cache:
          key: <<parameters.cache-id>>-dependency-cache-v2-{{ .Environment.CIRCLE_JOB }}-{{ checksum "<<parameters.path>>/<<parameters.dependency-file>>" }}
      - run:
          name: "<<parameters.package-manager>> install in <<parameters.path>>"
          command: |
            cd "<<parameters.path>>"
            [[ -e node_modules/ ]] || <<parameters.package-manager>> install
      - save_cache:
          key: <<parameters.cache-id>>-dependency-cache-v2-{{ .Environment.CIRCLE_JOB }}-{{ checksum "<<parameters.path>>/<<parameters.dependency-file>>" }}
          paths:
            - "<<parameters.path>>/node_modules/"

jobs:
  node-base: &node-base
    working_directory: ~/solc-js
    docker:
      - image: circleci/node
    parameters:
      run_coveralls:
        type: boolean
        default: false
    steps:
      - show-npm-version
      - checkout
      - install-dependencies:
          cache-id: solc-js
      - run:
          name: install-npm
          command: npm install
      - run:
          name: updateBinary
          command: npm run updateBinary
      - run:
          name: test
          command: npm run test
      - when:
          condition: <<parameters.run_coveralls>>
          steps:
            - run:
                name: coveralls
                command: npm run coveralls

  node-v10:
    <<: *node-base
    docker:
      - image: circleci/node:10
  node-v12:
    <<: *node-base
    docker:
      - image: circleci/node:12
  node-v14:
    <<: *node-base
    docker:
      - image: circleci/node:14
  node-v16:
    <<: *node-base
    docker:
      - image: circleci/node:16
  node-v17:
    <<: *node-base
    docker:
      - image: circleci/node:17
