workflows:
  version: 2.1
  node-multi-build:
    jobs:
      - node-v8
      - node-v10
      - node-v12:
          run_coveralls: true

version: 2.1
jobs:
  node-base: &node-base
    working_directory: ~/solc-js
    docker:
      - image: circleci/node
    parameters:
      run_coveralls:
        type: boolean
        default: false
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm run test
      - when:
          condition: <<parameters.run_coveralls>>
          steps:
            - run:
                name: coveralls
                command: npm run coveralls
      - save_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  node-v4:
    <<: *node-base
    docker:
      - image: circleci/node:4
  node-v6:
    <<: *node-base
    docker:
      - image: circleci/node:6
  node-v8:
    <<: *node-base
    docker:
      - image: circleci/node:8
  node-v10:
    <<: *node-base
    docker:
      - image: circleci/node:10
  node-v12:
    <<: *node-base
    docker:
      - image: circleci/node:12
